CREATE TABLE TB_LAYER4_SNIPER
(
  ID             NUMBER(19)                     NOT NULL,
  PALPITE_FINAL  VARCHAR2(50 BYTE),
  SCORE_SNIPER   NUMBER(10,4),
  DECISAO_FINAL  VARCHAR2(20 BYTE),
  DATA_L4        DATE                           DEFAULT SYSDATE
)
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PK_L4_SNIPER ON TB_LAYER4_SNIPER
(ID, PALPITE_FINAL)
LOGGING;

ALTER TABLE TB_LAYER4_SNIPER ADD (
  CONSTRAINT PK_L4_SNIPER
  PRIMARY KEY
  (ID, PALPITE_FINAL)
  USING INDEX PK_L4_SNIPER
  ENABLE VALIDATE);
